### ISSUE TITLE
Blanket 2.0 Roadmap

### ISSUE THREAD

**Issue by alex-seville** [alex-seville/blanket#378]
I'm going to develop a proper roadmap for Blanket 2.0, and I'm hoping to get feedback on the complete list of changes it should entail.  The following is a list of my priorities, but I'd love to hear what others would like changed/upgraded:
- [ ] source code needs to be more clearly organized/architected
- [ ] using `istanbul` for instrumenting
- [ ] supporting qunit, mocha, jasmine in their latest and second-to-latest versions
- [ ] using yuidocs to generate meaningful documentation for the project
- [ ] clean up `/test/` directory
- [ ] upgrade grunt
- [ ] upgrade build script
- [ ] update how tests are configured
- [ ] should be as backward compatible to Blanket 1.0 as possible

My plan is to take the finalized list, break it into issues, and work on them one at a time.  If anyone is interested in participating in the development, please let me know and a feature can be assigned to you.

I'll be pushing a new branch later today that will serve as the base for the new version.

I'm hoping this will both address support concerns that people have, while also ensuring that Blanket is built in a way that allows for future enhancements/fixes to be done with more ease.

Let me know what else you want!

**Comment by simonzack** [comment]
Is development still active? I would love to display coverage reports within the qunit test runner, using istanbul to instrument (so I get branch coverage information), like blanket.js is doing now.

**Comment by listepo** [comment]
+1

**Comment by alex-seville** [comment]
development is not active.  I'd love if there are people interested/motivated enough to take it over, but at the moment I don't have the time.

**Comment by listepo** [comment]
I want to help

**Comment by ffMathy** [comment]
I would also like to help.
